### ISSUE TITLE
How to arrange the filling order as from top to bottom when using new-line?

### ISSUE THREAD

**Issue by ReichYang** [gyli/PyWaffle#22]
Hi. I want to use the new-line arrangement for my plot.

This is what's shown in the documentation.

fig = plt.figure(
    FigureClass=Waffle,
    columns=10,
    values=[30, 16, 4],
    block_arranging_style='new-line',
    vertical=True
)

![image](https://user-images.githubusercontent.com/22743682/135178240-6b486a80-e900-48b1-8461-59a0202c89bf.png)

However, as you can see, for the orange ones, if they have to span multiple rows and cannot span multiple rows, the plot will try to fill out the last row first, leaving the top row of the category incomplete. Is there a way to reverse it so that within each category, the top rows get filled out first then the bottom rows and if multiple rows cannot be filled the last row will be incomplete instead of the first row.

**Comment by gyli** [comment]
Hi! By default it is plotting each category from top left to bottom right, and after applying vertical=True, the starting location is changed to bottom left. That's why you are seeing [30, 16, 4] in bottom to top direction. So to make the tail blocks at the "last rows" (top to bottom direction), you can simply flip the plot by specifying starting_location='NW'.

```
fig = plt.figure(
FigureClass=Waffle,
columns=10,
values=[30, 16, 4],
block_arranging_style='new-line',
vertical=True,
starting_location='NW'
)
```

**Comment by gyli** [comment]
Hi! By default it is plotting each category from bottom left to top right, that's why you are seeing [30, 16, 4] in bottom to top direction. So to make the tail blocks at the "last rows" (top to bottom direction), you can simply flip the plot by specifying starting_location='NW'.

```
fig = plt.figure(
FigureClass=Waffle,
columns=10,
values=[30, 16, 4],
block_arranging_style='new-line',
vertical=True,
starting_location='NW'
)
```

This section might be helpful: https://pywaffle.readthedocs.io/en/latest/examples/block_shape_spacing_location_direction_and_style.html#where-to-start-first-block
